# Declare a Service and a Deployment to deploy your application on the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-kdb
  labels:
    app: k8s-demo-kdb
spec:
  replicas: 1
  selector:
    matchLabels: #matches on template label, defaults to this in later api versions
      app: k8s-demo-kdb
  template:
    metadata:
      labels:
        app: k8s-demo-kdb
    spec:
      containers:
        - name: k8s-demo-kdb
          image: 163091829738.dkr.ecr.eu-west-1.amazonaws.com/k8s-demo-kdb
          ports:
            - containerPort: 8080
          env:
            - name: WELCOME_NAME
              value: Ken
            - name: SPRING_PROFILES_ACTIVE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-kdb
spec:
  type: ClusterIP
  selector: #matches on pod app-value , this means deployment app-label
    app: k8s-demo-kdb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
